import MainLayout from "@/components/main-layout";
import { pretendard } from "@/public/fonts/fonts";
import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Funnection",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.className}`}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
